sudo: false

language: node_js

node_js:
  - 7
  - 6

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb

install:
  - export CXX="g++-4.8"
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install -g npm@latest
  - npm install

script:
  - npm run test:node
  - npm run coverage
