sudo: false

language: node_js

addons:
  apt:
    packages:
      - libnss3-dev

node_js:
  - 7
  - 6

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install -g npm@latest
  - npm install

script:
  - npm run test:node
  - npm run test:electron
