sudo: false

language: node_js

addons:
  apt:
    packages:
      - xauth
      - xvfb
      - build-essential
      - git
      - clang
      - libdbus-1-dev
      - libgtk2.0-dev
      - libnotify-dev
      - libgnome-keyring-dev
      - libgconf2-dev
      - libasound2-dev
      - libcap-dev
      - libcups2-dev
      - libxtst-dev
      - libxss1
      - libnss3-dev
      - gcc-multilib
      - g++-multilib
      
node_js:
  - 7
  - 6

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install -g npm@latest
  - npm install

script:
  - npm run test:node
  - npm run test:electron
